{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "ingress-merge.fullname" . }}
  labels:
    app: {{ include "ingress-merge.name" . }}
    chart: {{ include "ingress-merge.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
{{- if .Values.rbac.podSecurityPolicy }}
  - apiGroups:
    - policy
    resources:
    - podsecuritypolicies
    verbs:
    - use
    resourceNames:
    - {{ include "ingress-merge.fullname" . }}
{{- end }}
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking
    resources:
      - ingresses
      - ingresses/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
{{ end }}
