{{ if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ingress-merge.fullname" . }}
  labels:
    app: {{ include "ingress-merge.name" . }}
    chart: {{ include "ingress-merge.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{ end }}
